<a href='https://www.hexnbit.com/'> <img src='https://www.hexnbit.com/wp-content/uploads/2019/09/hexnbit_final_66px.png'/> </a>

# Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task1

- Convert all characters of the word "PYTHON" to its decimal equivalent and then store them.
- Convert all the decimal equvalents back to characters 

**Hint:** Built in functions to do so are there to perform this task
Refer https://docs.python.org/3/library/functions.html

In [2]:
def chrtodec(str):
    dec = 0
    base = ord('0')
    for chr in str:
        dec = dec * 10 + ord(chr) - base
    return dec
chrtodec("PYTHON")

3648740

### Task2
- Raise 2 to the power 10

In [3]:
2 ** 10

1024

### Task3

- From the given list, starting from Japan, print alternate elements
- From the given list, print element at indexes 1,4,5,8 (**Hint**: Use for loop or list comprehension)

In [4]:
# Task 3
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]
res = [list1[i] for i in range(len(list1)) if i % 2 != 0]
  
# printing result 
print ("The alternate element list is : " + str(res))
for i in [1, 4, 5 ,8]:
    print(list1[i])

The alternate element list is : ['Japan', 'China', 'Africa', 'France', 'Germany']
Japan
Australia
Africa
Italy


### Task4

- From the given list, extract the "Hex" and print it

In [8]:
# Task 4
list2=[22,[4, [True, False], 6, 8], [888, 999,[111,222,["Hex"]]] ]
print(list2[2][2][2][0])

Hex


### Task5

- From the given dictionary, fetch the keyword "TOPD"

In [21]:
# Task 5
dict1={"Tevatron":["Technologies","Pvt","Ltd",{"Domains":["Embedded","IoT","AI","ML"],"Projects":["inhouse","TOPD"]}]}
print(dict1["Tevatron"][3]['Projects'][1])

TOPD


### Task6
There are 3 height categories

**167 and below  =**    Short <br>
**168 to 182     =**    Average <br>
**182 and above  =**    Tall<br>

Write a programe which gets the input from user and prints if the category the person fits in

**Hint**: Use function input()

In [27]:
val= int(input("enter your height"))
if val<168 :
    print(val)
    print("short")
elif val>167 and val<183 :
    print(val)
    print("average")
else :
    print(val)        
    print ("Tall")

180
average


### Task7

Using maximum 2 lines of code, generate all upper case alphabets

**Hint**: Refer ASCII Table

In [10]:
for c in range(65, 91):
        print(chr(c), end = " ");

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 

### Task8

Generate integers between (100 and 200) both inclusive, using NumPy

In [28]:
import numpy as np
x = np.random.randint(low=99, high=201, size=20)
print(x)

[165 101 180 132 119 196 144 184 141 178 112 132 164 161 166 191 190 199
 127 132]


### Task9

Print all even integers from the array created in Task8

In [29]:
import numpy as np
array=np.arange(100,201,2)
print("Array of all the even integers from 100 to 200 is:")
print(array) 

Array of all the even integers from 100 to 200 is:
[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]


### Task10

Print all 100 values from Standard Normal Distribution

In [28]:
import numpy as np
rand_num = np.random.normal(100,200,100)
print("100 numbers from a standard normal distribution:")
print(rand_num)

100 numbers from a standard normal distribution:
[  81.13897259 -268.40595223  243.15159586   21.81925416  123.90027835
  249.88055211  -21.92246933 -127.11450119  151.46653662  -48.25710313
  110.84151275   62.27611246   23.9762634    10.18628806 -108.90416146
  327.12696907 -230.67708114  179.08514252  542.92526531 -106.22030056
  264.39117198  618.40737075  -99.44873819  317.75488486  237.38913444
 -113.5594459    30.10517844  -24.37592454  144.5634917   105.4255047
  234.23593037  -12.52687305   98.78790582   20.03067064  479.22634246
 -139.33564873 -117.83772823  244.35357684  -84.82497637  -73.05198462
  197.02288603  240.84611248  -21.11498965  -24.10715023 -139.12231763
 -151.23126257  315.90363803  119.40908444  -14.97003404  240.19569393
  201.37200831   81.37184451  130.99502963   78.83039215  273.46443155
  309.02275854  325.69950989  194.18774099  279.18081635  118.09424873
  105.9092057    17.26021381   25.16551779 -107.82373735 -106.32896523
 -273.27069151  408.04912339 

### Task11

Create a NumPy array of random number, whose dimension attribute is equal to 4

In [30]:
import numpy as np
rand_int2 = np.random.randint(0,50,(4,4)) 
print( rand_int2)


[[38 36  1 48]
 [46  4 43 26]
 [47 29 30 19]
 [48  5  5  8]]


### Task12

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [30]:
import numpy as np
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

### Task13

Create a NumPy array of shape 5x5 and print the last 3 rows

In [34]:
import numpy as np
rand_int2 = np.random.randint(0,50,(5,5)) 
print( rand_int2)

print("last 3rows \n" , rand_int2[2 :5 ,:])

[[43 39 40 24 22]
 [32 28 25 22  9]
 [26 14 10 11  6]
 [ 8 26 26 37 33]
 [34 23 30 13 46]]
last 3rows 
 [[26 14 10 11  6]
 [ 8 26 26 37 33]
 [34 23 30 13 46]]


### Task14

Using the array created above in Task13, Print the first 2 columns

In [35]:
print("first 2 columns \n" , rand_int2[: ,0:2])

first 2 columns 
 [[43 39]
 [32 28]
 [26 14]
 [ 8 26]
 [34 23]]


### Task15

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [37]:
import numpy as np 
        
arr = [20,7,3,2,2,10,4,6,8,9,3,1,5,4,13,15,17,19,21,12,11,15,23,22,25]  
   
print("\nSum of arr : ", np.sum(arr)) 


Sum of arr :  277


In [38]:
import numpy
 
arr = numpy.array([20,7,3,2,2,10,4,6,8,9,3,1,5,4,13,15,17,19,21,12,11,15,23,22,25])

max_element = numpy.max(arr)
min_element = numpy.min(arr)
 
print('maximum element in the array is: ',
      max_element)
print('minimum element in the array is: ',
      min_element)

maximum element in the array is:  25
minimum element in the array is:  1


### Task16

In the array created above, print columns with indexes 1,3,4 without directly indexing them <br>
**Hint:** Make use of another list for indexing

### Task17
Read car_sales.csv

In [5]:
import pandas as pd

pd.read_csv("car_sales.csv")


Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0            1        Acura  Integra    Small       12.9   15.9       18.8   
1            2        Acura   Legend  Midsize       29.2   33.9       38.7   
2            3         Audi       90  Compact       25.9   29.1       32.3   
3            4         Audi      100  Midsize       30.8   37.7       44.6   
4            5          BMW     535i  Midsize       23.7   30.0       36.2   
..         ...          ...      ...      ...        ...    ...        ...   
88          89   Volkswagen  Eurovan      Van       16.6   19.7       22.7   
89          90   Volkswagen   Passat  Compact       17.6   20.0       22.4   
90          91   Volkswagen  Corrado   Sporty       22.9   23.3       23.7   
91          92        Volvo      240  Compact       21.8   22.7       23.5   
92          93        Volvo      850  Midsize       24.8   26.7       28.5   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
0         25           31                None  ...          5    177   
1         18           25  Driver & Passenger  ...          5    195   
2         20           26         Driver only  ...          5    180   
3         19           26  Driver & Passenger  ...          6    193   
4         22           30         Driver only  ...          4    186   
..       ...          ...                 ...  ...        ...    ...   
88        17           21                None  ...          7    187   
89        21           30                None  ...          5    180   
90        18           25                None  ...          4    159   
91        21           28         Driver only  ...          5    190   
92        20           28  Driver & Passenger  ...          5    184   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
0         102     68           37            26.5         11.0    2705   
1         115     71           38            30.0         15.0    3560   
2         102     67           37            28.0         14.0    3375   
3         106     70           37            31.0         17.0    3405   
4         109     69           39            27.0         13.0    3640   
..        ...    ...          ...             ...          ...     ...   
88        115     72           38            34.0          NaN    3960   
89        103     67           35            31.5         14.0    2985   
90         97     66           36            26.0         15.0    2810   
91        104     67           37            29.5         14.0    2985   
92        105     69           38            30.0         15.0    3245   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88  non-USA  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 28 columns]

### Task18
Sort data frame in ascending order of the Price column

In [3]:
import pandas as pd
carsDf = pd.read_csv("car_sales.csv")
carsDf = carsDf.sort_values(by=['Price'], ascending=False)
carsDf.head(5)

Unnamed: 0   Manufacturer     Model     Type  Min.Price  Price  Max.Price  \
58          59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0   
47          48       Infiniti       Q45  Midsize       45.4   47.9       50.4   
10          11       Cadillac   Seville  Midsize       37.5   40.1       42.7   
18          19      Chevrolet  Corvette   Sporty       34.6   38.0       41.5   
3            4           Audi       100  Midsize       30.8   37.7       44.6   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
58        19           25  Driver & Passenger  ...          5    187   
47        17           22         Driver only  ...          5    200   
10        16           25  Driver & Passenger  ...          5    204   
18        17           25         Driver only  ...          2    179   
3         19           26  Driver & Passenger  ...          6    193   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
58        110     69           37            27.0         15.0    3525   
47        113     72           42            29.0         15.0    4000   
10        111     74           44            31.0         14.0    3935   
18         96     74           43             NaN          NaN    3380   
3         106     70           37            31.0         17.0    3405   

     Origin                Make  
58  non-USA  Mercedes-Benz 300E  
47  non-USA        Infiniti Q45  
10      USA    Cadillac Seville  
18      USA  Chevrolet Corvette  
3   non-USA            Audi 100  

[5 rows x 28 columns]

### Task19
Print number of unique car manufacturers in the data

In [4]:
import pandas as pd

data = pd.read_csv("car_sales.csv")

unique_value = data["Manufacturer"].nunique()

print(unique_value)

32


### Task20
Print the maximum Wheelbase from the data

In [48]:
import pandas as pd
df = pd.read_csv("car_sales.csv")

max_Wheelbase =df['Wheelbase'].max()
print(max_Wheelbase)

FileNotFoundError: [Errno 2] No such file or directory: 'car_sales.csv'

### Task21
Print the car Model which has maximum Wheelbase

### Task22

Print the Details of car with maximum passenger capacity