<a href='https://www.hexnbit.com/'> <img src='https://www.hexnbit.com/wp-content/uploads/2019/09/hexnbit_final_66px.png'/> </a>

# Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task1

- Convert all characters of the word "PYTHON" to its decimal equivalent and then store them.
- Convert all the decimal equvalents back to characters 

**Hint:** Built in functions to do so are there to perform this task
Refer https://docs.python.org/3/library/functions.html

In [8]:
#converting "PYTHON" into decimalequvalents and storing them in a list 
dec_eq=[]
str1="PYTHON"
for x in str1:
    
    value=ord(x)
    dec_eq.append(value)
    
print(dec_eq)  

[80, 89, 84, 72, 79, 78]


In [3]:
char_eq=[]
for x in dec_eq:
    value=chr(x)
    char_eq.append(value)
    
print(char_eq)    

['P', 'Y', 'T', 'H', 'O', 'N']


### Task2
- Raise 2 to the power 10

In [5]:
pow(2,10) and 2**10    #both ways can be used

1024

### Task3

- From the given list, starting from Japan, print alternate elements
- From the given list, print element at indexes 1,4,5,8 (**Hint**: Use for loop or list comprehension)

In [15]:
# Task 3
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]
res = [list1[i] for i in range(len(list1)) if i % 2 != 0]
  
# printing result 
print ("The alternate element list is : " + str(res))


The alternate element list is : ['Japan', 'China', 'Africa', 'France', 'Germany']


In [16]:
#specific elements
for i in [1,4,5,8]:
    print(list1[i])

Japan
Australia
Africa
Italy


### Task4

- From the given list, extract the "Hex" and print it

In [27]:
# Task 4
list2=[22,[4, [True, False], 6, 8], [888, 999,[111,222,["Hex"]]] ]
print(list2[2][2][2])

['Hex']


### Task5

- From the given dictionary, fetch the keyword "TOPD"

In [17]:
# Task 5
dict1={"Tevatron":["Technologies","Pvt","Ltd",{"Domains":["Embedded","IoT","AI","ML"],"Projects":["inhouse","TOPD"]}]}
print(dict1["Tevatron"][3]['Projects'][1])

dict_keys(['Tevatron'])
dict_items([('Tevatron', ['Technologies', 'Pvt', 'Ltd', {'Domains': ['Embedded', 'IoT', 'AI', 'ML'], 'Projects': ['inhouse', 'TOPD']}])])
['Technologies', 'Pvt', 'Ltd', {'Domains': ['Embedded', 'IoT', 'AI', 'ML'], 'Projects': ['inhouse', 'TOPD']}]


### Task6
There are 3 height categories

**167 and below  =**    Short <br>
**168 to 182     =**    Average <br>
**182 and above  =**    Tall<br>

Write a programe which gets the input from user and prints if the category the person fits in

**Hint**: Use function input()

In [2]:
val= int(input("enter your height"))
if val<168 :
    print(val)
    print("short")
elif val>167 and val<183 :
    print(val)
    print("average")
else :
    print(val)        
    print ("Tall")

180
average


### Task7

Using maximum 2 lines of code, generate all upper case alphabets

**Hint**: Refer ASCII Table

In [4]:
for c in range(65, 91):
        print(chr(c), end = " ");

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 

### Task8

Generate integers between (100 and 200) both inclusive, using NumPy

In [18]:
import numpy as np
x = np.random.randint(low=99, high=201, size=10)
print(x)

[176 113 117 150 179 117 154 145 193 134]


### Task9

Print all even integers from the array created in Task8

In [20]:
import numpy as np
array=np.arange(100,201,2)
print("Array of all the even integers from 100 to 200")
print(array) 

Array of all the even integers from 100 to 200
[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]


### Task10

Print all 100 values from Standard Normal Distribution

In [21]:
import numpy as np
rand_num=np.random.randn(100)
print("100 numbers from a standard normal distribution:")
print(rand_num)

100 numbers from a standard normal distribution:
[-0.72927147 -0.02181898  1.59639645 -1.76371048 -0.86808161 -2.69641148
 -0.84873888  1.74065792  0.04665374 -1.9694307  -0.20797809 -1.53823307
 -0.71272283  1.20604632 -1.61037803 -0.90774665  0.73298769  0.18493202
  0.814885    0.32812908  0.63608411 -0.47266033 -0.70982831  1.73702997
  0.58229805 -0.64283561 -1.12860793 -0.79998183 -1.02888619 -0.01823938
  0.36505775  1.65781612 -1.08649417 -0.93270138 -0.2625364  -0.43162148
 -1.49117403 -0.74906501  0.87992539  0.74168424  0.04948196 -0.24802262
  0.50714451  1.1134405  -0.47822825  0.87681557 -0.04810765  0.26755891
 -1.49880002  0.18487092 -0.48868699  1.68567304  0.62528474 -1.05183452
 -3.4779963  -0.49931337  0.43150411 -0.65687682 -1.4434555  -0.15646759
 -1.37484392 -0.66759646  0.45773818  0.85017447  1.74991286 -0.0203442
 -1.05224392  0.58587243  0.26374622 -0.88801992 -0.06524834  0.59425304
 -0.4008647  -0.82700426 -0.49916779  0.73628051  0.40989611  0.01053743
 -0

### Task11

Create a NumPy array of random number, whose dimension attribute is equal to 4

In [3]:
import numpy as np
rand_int2 = np.random.randint(0,50,(4,4)) 
print( rand_int2)

[[42  3  9 20]
 [27 32 30  7]
 [17 16 14 16]
 [45  9 28 16]]


### Task12

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [23]:
import numpy as np
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

### Task13

Create a NumPy array of shape 5x5 and print the last 3 rows

In [4]:
import numpy as np
rand_int2 = np.random.randint(0,50,(5,5)) 
print( rand_int2)

print("last 3rows \n" , rand_int2[2 :5 ,:])

[[22  2  5  5 34]
 [33 46 21  9 27]
 [36  5 22  3 21]
 [46 10 42 34 36]
 [10  7 14 33 30]]
last 3rows 
 [[36  5 22  3 21]
 [46 10 42 34 36]
 [10  7 14 33 30]]


### Task14

Using the array created above in Task13, Print the first 2 columns

In [41]:
print("first 2 columns \n" , rand_int2[: ,0:2])

printing first two columns
[[128 114]
 [161 157]
 [164 118]
 [122 110]
 [123 147]]


### Task15

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [5]:
import numpy as np 
        
arr = [20,7,3,2,2,10,4,6,8,9,3,1,5,4,13,15,17,19,21,12,11,15,23,22,25]  
   
print("\nSum of arr : ", np.sum(arr)) 


Sum of arr :  277


In [6]:
import numpy
 
arr = numpy.array([20,7,3,2,2,10,4,6,8,9,3,1,5,4,13,15,17,19,21,12,11,15,23,22,25])

max_element = numpy.max(arr)
min_element = numpy.min(arr)
 
print('maximum element in the array is: ',
      max_element)
print('minimum element in the array is: ',
      min_element)

maximum element in the array is:  25
minimum element in the array is:  1


### Task16

In the array created above, print columns with indexes 1,3,4 without directly indexing them <br>
**Hint:** Make use of another list for indexing

In [53]:
mul_arr=arr.reshape(5,5)
print(mul_arr)
print("columns with indexes 1,3,4")
print(mul_arr[:,1:5])
#not able to do the same

[[2 6 0 0 5]
 [4 3 1 2 7]
 [2 6 5 0 7]
 [6 8 1 5 6]
 [2 1 8 8 1]]
columns with indexes 1,3,4
[[6 0 0 5]
 [3 1 2 7]
 [6 5 0 7]
 [8 1 5 6]
 [1 8 8 1]]


### Task17
Read car_sales.csv

In [54]:
import pandas as pd

pd.read_csv("car_sales(1).csv")

Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0            1        Acura  Integra    Small       12.9   15.9       18.8   
1            2        Acura   Legend  Midsize       29.2   33.9       38.7   
2            3         Audi       90  Compact       25.9   29.1       32.3   
3            4         Audi      100  Midsize       30.8   37.7       44.6   
4            5          BMW     535i  Midsize       23.7   30.0       36.2   
..         ...          ...      ...      ...        ...    ...        ...   
88          89   Volkswagen  Eurovan      Van       16.6   19.7       22.7   
89          90   Volkswagen   Passat  Compact       17.6   20.0       22.4   
90          91   Volkswagen  Corrado   Sporty       22.9   23.3       23.7   
91          92        Volvo      240  Compact       21.8   22.7       23.5   
92          93        Volvo      850  Midsize       24.8   26.7       28.5   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
0         25           31                None  ...          5    177   
1         18           25  Driver & Passenger  ...          5    195   
2         20           26         Driver only  ...          5    180   
3         19           26  Driver & Passenger  ...          6    193   
4         22           30         Driver only  ...          4    186   
..       ...          ...                 ...  ...        ...    ...   
88        17           21                None  ...          7    187   
89        21           30                None  ...          5    180   
90        18           25                None  ...          4    159   
91        21           28         Driver only  ...          5    190   
92        20           28  Driver & Passenger  ...          5    184   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
0         102     68           37            26.5         11.0    2705   
1         115     71           38            30.0         15.0    3560   
2         102     67           37            28.0         14.0    3375   
3         106     70           37            31.0         17.0    3405   
4         109     69           39            27.0         13.0    3640   
..        ...    ...          ...             ...          ...     ...   
88        115     72           38            34.0          NaN    3960   
89        103     67           35            31.5         14.0    2985   
90         97     66           36            26.0         15.0    2810   
91        104     67           37            29.5         14.0    2985   
92        105     69           38            30.0         15.0    3245   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88  non-USA  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 28 columns]

### Task18
Sort data frame in ascending order of the Price column

In [63]:
import pandas as pd
carsDf = pd.read_csv("car_sales(1).csv")
carsDf = carsDf.sort_values('Price')
carsDf.head(93)

Unnamed: 0   Manufacturer     Model     Type  Min.Price  Price  Max.Price  \
30          31           Ford   Festiva    Small        6.9    7.4        7.9   
43          44        Hyundai     Excel    Small        6.8    8.0        9.2   
52          53          Mazda       323    Small        7.4    8.3        9.1   
38          39            Geo     Metro    Small        6.7    8.4       10.0   
79          80         Subaru     Justy    Small        7.3    8.4        9.5   
..         ...            ...       ...      ...        ...    ...        ...   
3            4           Audi       100  Midsize       30.8   37.7       44.6   
18          19      Chevrolet  Corvette   Sporty       34.6   38.0       41.5   
10          11       Cadillac   Seville  Midsize       37.5   40.1       42.7   
47          48       Infiniti       Q45  Midsize       45.4   47.9       50.4   
58          59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
30        31           33                None  ...          4    141   
43        29           33                None  ...          5    168   
52        29           37                None  ...          4    164   
38        46           50                None  ...          4    151   
79        33           37                None  ...          4    146   
..       ...          ...                 ...  ...        ...    ...   
3         19           26  Driver & Passenger  ...          6    193   
18        17           25         Driver only  ...          2    179   
10        16           25  Driver & Passenger  ...          5    204   
47        17           22         Driver only  ...          5    200   
58        19           25  Driver & Passenger  ...          5    187   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
30         90     63           33            26.0         12.0    1845   
43         94     63           35            26.0         11.0    2345   
52         97     66           34            27.0         16.0    2325   
38         93     63           34            27.5         10.0    1695   
79         90     60           32            23.5         10.0    2045   
..        ...    ...          ...             ...          ...     ...   
3         106     70           37            31.0         17.0    3405   
18         96     74           43             NaN          NaN    3380   
10        111     74           44            31.0         14.0    3935   
47        113     72           42            29.0         15.0    4000   
58        110     69           37            27.0         15.0    3525   

     Origin                Make  
30      USA        Ford Festiva  
43  non-USA       Hyundai Excel  
52  non-USA           Mazda 323  
38  non-USA           Geo Metro  
79  non-USA        Subaru Justy  
..      ...                 ...  
3   non-USA            Audi 100  
18      USA  Chevrolet Corvette  
10      USA    Cadillac Seville  
47  non-USA        Infiniti Q45  
58  non-USA  Mercedes-Benz 300E  

[93 rows x 28 columns]

### Task19
Print number of unique car manufacturers in the data

In [64]:
import pandas as pd

data = pd.read_csv("car_sales(1).csv")

unique_value = data["Manufacturer"].nunique()

print(unique_value)

32


### Task20
Print the maximum Wheelbase from the data

In [65]:
import pandas as pd
df = pd.read_csv("car_sales(1).csv")

max_Wheelbase =df['Wheelbase'].max()
print(max_Wheelbase)

119


### Task21
Print the car Model which has maximum Wheelbase

### Task22

Print the Details of car with maximum passenger capacity